### ISSUE TITLE
Filtro de serviços nao funciona na primeira vez que a página é carregada

### ISSUE THREAD

**Issue by alexlopespereira** [alexlopespereira/diagnostico_servicos#11]
Sendo necessário fazer um refresh para que o filtro funcione.

**Comment by alexlopespereira** [comment]
Me refiro ao filtro de serviços no questionario do limesurvey

**Comment by Hiroshi18** [comment]
Inserindo este script é possível forcar que ele recarregue a pagine e mantenha na pagina atual

<script type="text/javascript">
$(document).ready(function(){    
    //Check if the current URL contains '#'
    if(document.URL.indexOf("#")==-1){
        // Set the URL to whatever it was plus "#".
        url = document.URL+"#";
        location = "#";

        //Reload the page
        location.reload(true);
    }
});
</script>
