### ISSUE TITLE
Criar questao com slider (para o usuario informar um dado numérico)

### ISSUE THREAD

**Issue by alexlopespereira** [alexlopespereira/diagnostico_servicos#7]
Criar questao cujo dado de entrada seja numero e a maneira do usuario informar seja um slider. Alguns dados precisam ser bem controlados. Alguns usuários preenchem um zero a mais, e isso impacta relevantemente nos custos dos serviços

**Comment by alexlopespereira** [comment]
![Screenshot.png](https://images.zenhubusercontent.com/5ca7a3ca44407c6b94d3b6fa/116f1ffd-8edb-4e3b-b962-46260b7fca73)

**Comment by Hiroshi18** [comment]
[Slider Question.pdf](https://github.com/alexlopespereira/diagnostico_servicos/files/3113713/Slider.Question.pdf)

**Comment by Hiroshi18** [comment]
Aqui tem um pdf de como fazer question com sliders
